library(datasets)
source("load_data_by_date.R")
png(file="plot2.png", width=480, height=480, units="px", bg ="transparent")
with(power_df,plot(DateTime,Global_active_power, type="l", xlab="",ylab="Global Active Power (kilowatts)"))
dev.off()